# Feature 4: Data Dictionary

In [1]:
# Import pandas library.
import pandas as pd

In [10]:
# Create a data dictionary.
Data_Dictionary = {'ID Rank':['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'],
                   'Variable':['Metro_Pop_2020_DF1', 'CBSA', 'City_Metro', 'LSAD', 'Date', 'Population', 'Metro_Pop_2000_DF2', 'Population_2000',
                               'Population_2010', 'GDP_Metro_DF3', 'Description', 'LineCode', 'Merged_Data', 'PopulationDiff', 'DF1_MetPop2020', 'DF2_Metro_Pop2000', 'DF3_Metro_GDP'],
                   'Data_Type':['DataFrame', 'int64', 'object', 'object', 'int64', 'int64', 'DataFrame', 'int64', 'int64', 'DataFrame', 'object', 'int64',
                                'DataFrame', 'int64', 'DataFrame', 'DataFrame', 'DataFrame'],
                   'Description':['DataFrame of 2020 population data', 'Unique metro area code', 'Name of metro area', 'Metro area', 'Date',
                                  'Population of metro area for year 2020', 'DataFrame of 2000 and 2010 population data', 'Population of metro area for year 2000',
                                  'Population of metro area for year 2010', 'DataFrame of 2021 GDP data', 'Current dollar GDP', 'Number from dataset',
                                  'New DataFrame created by merging two others', 'New column created by using two others', 'Subset of Metro_Pop_2020_DF1 DataFrame',
                                  'Subset of Metro_Pop_2000_DF2 DataFrame', 'Subset of GDP_Metro_DF3 DataFrame']}

In [12]:
# Create variable and link to DataFrame.
Data = pd.DataFrame(Data_Dictionary)

In [13]:
# Display data dictiondary.
Data

,ID Rank,Variable,Data_Type,Description
0,1,Metro_Pop_2020_DF1,DataFrame,DataFrame of 2020 population data
1,2,CBSA,int64,Unique metro area code
2,3,City_Metro,object,Name of metro area
3,4,LSAD,object,Metro area
4,5,Date,int64,Date
5,6,Population,int64,Population of metro area for year 2020
6,7,Metro_Pop_2000_DF2,DataFrame,DataFrame of 2000 and 2010 population data
7,8,Population_2000,int64,Population of metro area for year 2000
8,9,Population_2010,int64,Population of metro area for year 2010
9,10,GDP_Metro_DF3,DataFrame,DataFrame of 2021 GDP data
10,11,Description,object,Current dollar GDP
11,12,LineCode,int64,Number from dataset
12,13,Merged_Data,DataFrame,New DataFrame created by merging two others
13,14,PopulationDiff,int64,New column created by using two others
14,15,DF1_MetPop2020,DataFrame,Subset of Metro_Pop_2020_DF1 DataFrame
15,16,DF2_Metro_Pop2000,DataFrame,Subset of Metro_Pop_2000_DF2 DataFrame
16,17,DF3_Metro_GDP,DataFrame,Subset of GDP_Metro_DF3 DataFrame